# Generated by Django 6.0.7 on 2026-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='feels_like',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='sunrise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='sunset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='visibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
