# Generated by Django 6.0.7 on 2026-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_searchhistory_feels_like_searchhistory_sunrise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='cloudiness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='temp_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
