# Generated by Django 6.0.7 on 2026-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_searchhistory_cloudiness_searchhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='uv_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
