# Generated by Django 6.0.7 on 2026-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_searchhistory_uv_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='aqi_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
